import type { Metadata } from "next";
import "./globals.css";

import { Inter } from "next/font/google";

import { cn } from "../lib/utils";
import ClientOnly from "../components/clientOnly";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Translator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.className
        )}
      >
        <ClientOnly>{children}</ClientOnly>
      </body>
    </html>
  );
}
